name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy_terraform_resources:
    runs-on: ubuntu-latest
    steps:
      - name: Download Terraform State
        uses: actions/download-artifact@v2
        with:
          name: terraform-state
          path: terraform

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Destroy Terraform Resources
        run: |
          if [ "${{ secrets.ENVIRONMENT }}" = "dev" ]; then
            cd dev
            terraform destroy -auto-approve
          elif [ "${{ secrets.ENVIRONMENT }}" = "prod" ]; then
            cd prod
            terraform destroy -auto-approve
          elif [ "${{ secrets.ENVIRONMENT }}" = "qa" ]; then
            cd qa
            terraform destroy -auto-approve
          else
            echo "Invalid environment specified."
            exit 1
          fi
        working-directory: ./terraform
